version: "3"
services:
    backend:
        build: .
        restart: always
        deploy:
            replicas: 5
        # ports:
        #     - 8000:8000
        environment:
            PYTHONUNBUFFERED: 0
            MONGO_HOST: database
            MONGO_PORT: 27017
            ZOOKEEPER_HOST: zookeeper
            ZOOKEEPER_PORT: 2181
            DEFAULT_ID_COUNT: 100000
            TOTAL_POD_COUNT: 5
            HOSTNAME: "app-101"
        links:
            - "database:database"
        depends_on:
            - database
        networks:
            - backend-network
        volumes: 
            - ../datas/media:/media
            - ../datas/static:/static
    database:
        image: mongo
        container_name: database
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ../datas/db:/data/db
        networks:
            - backend-network
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
            - 8080:8080
        volumes:
            - ../datas/zookeeper/data:/data
            - ../datas/zookeeper/datalog:/datalog
        networks:
            - backend-network
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8000:8000
        restart: always
        command: 'bash -c "nginx -g ''daemon off;''"'
        depends_on:
            - database
            - zookeeper
            - backend
        networks:
            - backend-network

networks:
    backend-network:
        driver: bridge